[package]
name = "assets"
version.workspace = true
edition.workspace = true
publish.workspace = true

[lib]
name = "assets"
path = "src/assets.rs"

[dependencies]
rust-embed = { workspace = true }

[build-dependencies]
