[package]
name = "scene_graph"
version.workspace = true
edition.workspace = true
publish.workspace = true

[lib]
name = "scene_graph"
path = "src/scene_graph.rs"

[dependencies]
gpui = { workspace = true }
slotmap = { workspace = true }
node = { path = "../node" }
