[package]
name = "theme"
version.workspace = true
edition.workspace = true
publish.workspace = true

[lib]
name = "theme"
path = "src/theme.rs"

[dependencies]
gpui = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
